# -*- coding: utf-8 -*-
"""1620.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BId7UskzZ0PxdVZ8gioh0BNNOk9v7jW6
"""

# 나는야 포켓몬 마스터 이다솜
n, m = map(int, input().split())
dogam = {0: '0'}
for i in range(1,n+1):
  dogam[str(i)] = input()

for j in range(m):
  check = input()
  if check in dogam: # key(숫자)
    print(dogam.get(check))
  else: # value(문자열)
    for k, v in dogam.items():
      if v == "check":
        print(k)